name: "Task"
description: "Create new meta task"
labels: ["overview", "1. to develop"]
body:
  - type: textarea
    id: task-descr
    attributes:
      label: Describe the task
      description: Describe the task
      render: markdown
    validations:
      required: true
  - type: checkboxes
    id: components-affected
    attributes:
      label: Affected components
      description: Select the components that need to be changed.
      options:
        - label: Calendar
        - label: Calendar Resource Management
        - label: Contacts
        - label: Mail
        - label: cdav-library
        - label: nextcloud/calendar-availability-vue
        - label: nextcloud/calendar-js
  - type: textarea
    id: to-do
    attributes:
      label: To do
      description: Please add your task list on the form below
    validations:
      required: true
