name: "Task Report:  Groupware"
description: "Create new meta task"
title: "[Task]: "
labels: ["task", "1. to develop"]
assignees:
  - octocat
body:
  - type: textarea
    id: list-items
    attributes:
      label: Task list
      description: Please add your task list on the form below
      placeholder: Task list
      value: "Task list"
    validations:
      required: true
  - type: checkboxes
    id: version
    attributes:
      label: List of the affected Apps
      description: What app does this task belongs to?
      options:
        - label: Calendar
        - label: Calendar Resource Management
        - label: Contacts
        - label: Mail
        - label: cdav-library
        - label: nextcloud/calendar-availability-vue
        - label: nextcloud/calendar-js
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
