name: "Task"
description: "Create new meta task"
labels: ["overview", "1. to develop"]
body:
  - type: markdown
    attributes:
      value: "Task list"
  - type: checkboxes
    id: apps-affected
    attributes:
      label: List of the affected Apps
      description: What app does this task belongs to?
      options:
        - label: Calendar
        - label: Calendar Resource Management
        - label: Contacts
        - label: Mail
        - label: cdav-library
        - label: nextcloud/calendar-availability-vue
        - label: nextcloud/calendar-js
