name: "Task Report:  Groupware"
description: "Create new meta task"
title: "[Task]: "
labels: ["task", "1. to develop"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please add your task list on the form below
  - type: textarea
    id: list-items
    attributes:
      label: Task list
      description: List the tasks that you are planning to work on or assign to the team
      placeholder: Task list
      value: "Task list"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: App
      description: What app does this task belong to?
      options:
        - Calendar
        - Calendar Resource Management
        - Contacts
        - Mail
        - cdav-library
        - @nextcloud/calendar-availability-vue
        - @nextcloud/calendar-js
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
